"""DEPRECATED - Drugs now come from OpenFDA API. Kept for reference only."""
import json
import logging
import re

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# Common drug name patterns
DRUG_NAME_TRANSLATIONS = {
    "Low Dose": "Li\u1ec1u th\u1ea5p",
    "Extra Strength": "T\u0103ng c\u01b0\u1eddng",
    "Maximum Strength": "T\u1ed1i \u0111a",
    "Extended Release": "Ph\u00f3ng th\u00edch k\u00e9o d\u00e0i",
    "Delayed Release": "Gi\u1ea3i ph\u00f3ng ch\u1eadm",
    "Enteric Coated": "Bao tan trong ru\u1ed9t",
    "Coated": "Bao ph\u1ee7",
    "Dye Free": "Kh\u00f4ng ph\u1ea9m m\u00e0u",
    "Infants": "Tr\u1ebb em",
    "Children": "Tr\u1ebb em",
    "Adult": "Ng\u01b0\u1eddi l\u1edbn",
    "Junior": "Thi\u1ebfu nhi",
    "Concentrated": "\u0110\u1eadm \u0111\u1eb7c",
    "Regular Strength": "Ti\u00eau chu\u1ea9n",
    "Sugar Free": "Kh\u00f4ng \u0111\u01b0\u1eddng",
    "Alcohol Free": "Kh\u00f4ng c\u1ed3n",
    "Once Daily": "M\u1ed7i ng\u00e0y m\u1ed9t l\u1ea7n",
    "BID": "Hai l\u1ea7n m\u1ed7i ng\u00e0y",
    "Plus": "Plus",
    "With": "V\u1edbi",
    "And": "V\u00e0",
    "Pain Reliever": "Gi\u1ea3m \u0111au",
    "Pain Relief": "Gi\u1ea3m \u0111au",
    "Cough Syrup": "Si r\u00f4 ho",
    "Cough": "Ho",
    "Cold": "C\u1ea3m l\u1ea1nh",
    "Allergy": "D\u1ecb \u1ee9ng",
    "Sinus": "Xoang",
    "Nasal": "M\u0169i",
    "Decongestant": "Th\u00f4ng m\u0169i",
    "Expectorant": "Long \u0111\u1eddm",
    "Antihistamine": "Kh\u00e1ng histamin",
    "First Aid": "S\u01a1 c\u1ee9u",
    "Triple Antibiotic": "Kh\u00e1ng sinh ba",
    "Antibiotic": "Kh\u00e1ng sinh",
    "Relieving": "Gi\u1ea3m",
    "Balm": "D\u1ea7u",
    "Inhalation": "Thu\u1ed1c h\u00edt",
    "Spray": "X\u1ecbt",
    "Drops": "Thu\u1ed1c nh\u1ecf",
    "Tablets": "Vi\u00ean n\u00e9n",
    "Capsules": "Vi\u00ean nang",
    "Injection": "Thu\u1ed1c ti\u00eam",
    "Solution": "Dung d\u1ecbch",
    "Suspension": "H\u1ed7n d\u1ecbch",
    "Cream": "Kem b\u00f4i",
    "Ointment": "Thu\u1ed1c m\u1ee1",
    "Patch": "Mi\u1ebfng d\u00e1n",
    "Syrup": "Si r\u00f4",
    "Lotion": "Kem d\u01b0\u1ee1ng",
    "Gel": "Gel",
    "Mouthwash": "N\u01b0\u1edbc s\u00fac mi\u1ec7ng",
    "Toothpaste": "Kem \u0111\u00e1nh r\u0103ng",
    "Shampoo": "D\u1ea7u g\u1ed9i",
    "Soap": "X\u00e0 ph\u00f2ng",
    "Liquid": "Dung d\u1ecbch",
    "Powder": "B\u1ed9t",
    "Hydrochloride": "Hydrochlorid",
    "Sulfate": "Sulfat",
    "Bisulfate": "Bisulfat",
    "Phosphate": "Phosphat",
    "Sodium": "Natri",
    "Potassium": "Kali",
    "Calcium": "Canxi",
    "Magnesium": "Magie",
    "Zinc": "K\u1ebdm",
    "Iron": "S\u1eaft",
    "Acetate": "Acetat",
    "Citrate": "Citrat",
    "Carbonate": "Cacbonat",
    "Aspart": "Aspart",
    "Glargine": "Glargin",
    "Lispro": "Lispro",
    "Degludec": "Degludec",
    "Glipizide": "Glipizid",
    "Metformin": "Metformin",
    "Ezetimibe": "Ezetimib",
    "Benazepril": "Benazepril",
    "Olmesartan": "Olmesartan",
    "Medoxomil": "Medoxomil",
    "Clavulanate": "Clavulanat",
    "Formoterol": "Formoterol",
    "Fumarate": "Fumarat",
    "Salmeterol": "Salmeterol",
    "Dihydrate": "Dihydrat",
    "Trihydrate": "Trihydrat",
    "Dexamethasone": "Dexamethason",
    "Codeine": "Codein",
    "Morphine": "Morphin",
    "Tramadol": "Tramadol",
    "Oxycodone": "Oxycodon",
    "Hydrocodone": "Hydrocodon",
    "Bitartrate": "Bitartrat",
    "Bromide": "Bromid",
    "Albuterol": "Albuterol",
    "Propionate": "Propionat",
    "Hydrochlorothiazide": "Hydrochlorothiazid",
    "Insurance": "B\u1ea3o hi\u1ec3m",
}

# Replacement patterns: sort by length descending for longest match first
DRUG_NAME_PATTERNS = sorted(DRUG_NAME_TRANSLATIONS.items(), key=lambda x: -len(x[0]))


def translate_drug_name(name: str) -> str:
    for eng, vie in DRUG_NAME_PATTERNS:
        pattern = re.compile(re.escape(eng), re.IGNORECASE)
        name = pattern.sub(vie, name)
    # Also translate active ingredient names in parentheses
    def trans_ingredient(m):
        inner = m.group(1)
        translated = translate_text(inner)
        # Clean up excessive spaces
        translated = re.sub(r'\s+', ' ', translated).strip()
        return f"({translated})" if translated else f"({inner})"
    name = re.sub(r'\(([^)]+)\)', trans_ingredient, name)
    name = re.sub(r'\s+', ' ', name).strip()
    # Remove double spaces from empty article removal
    name = re.sub(r'\s+', ' ', name).strip()
    return name


# General medical text translation
MEDICAL_DICT = {
    # Symptoms
    "pain": "\u0111au",
    "aches": "\u0111au nh\u1ee9c",
    "cramps": "chu\u1ed9t r\u00fat",
    "swelling": "s\u01b0ng",
    "inflammation": "vi\u00eam",
    "redness": "\u0111\u1ecf",
    "itching": "ng\u1ee9a",
    "burning": "b\u1ecfng r\u00e1t",
    "bleeding": "ch\u1ea3y m\u00e1u",
    "discharge": "d\u1ecbch ti\u1ebft",
    "fever": "s\u1ed1t",
    "chills": "\u1edbn l\u1ea1nh",
    "cough": "ho",
    "sneeze": "h\u1eaft h\u01a1i",
    "runny nose": "s\u1ed5 m\u0169i",
    "stuffy nose": "ngh\u1eb9t m\u0169i",
    "sore throat": "\u0111au h\u1ecdng",
    "headache": "\u0111au \u0111\u1ea7u",
    "migraine": "\u0111au n\u1eeda \u0111\u1ea7u",
    "dizziness": "ch\u00f3ng m\u1eb7t",
    "vertigo": "ch\u00f3ng m\u1eb7t",
    "fatigue": "m\u1ec7t m\u1ecfi",
    "weakness": "y\u1ebfu",
    "nausea": "bu\u1ed3n n\u00f4n",
    "vomiting": "n\u00f4n",
    "diarrhea": "ti\u00eau ch\u1ea3y",
    "constipation": "t\u00e1o b\u00f3n",
    "indigestion": "kh\u00f3 ti\u00eau",
    "heartburn": "\u1ee3 n\u00f3ng",
    "bloating": "\u0111\u1ea7y h\u01a1i",
    "gas": "\u0111\u1ea7y h\u01a1i",
    "stomach upset": "kh\u00f3 ch\u1ecbu d\u1ea1 d\u00e0y",
    "loss of appetite": "ch\u00e1n \u0103n",
    "weight loss": "gi\u1ea3m c\u00e2n",
    "weight gain": "t\u0103ng c\u00e2n",
    "insomnia": "m\u1ea5t ng\u1ee7",
    "drowsiness": "bu\u1ed3n ng\u1ee7",
    "sleeplessness": "m\u1ea5t ng\u1ee7",
    "anxiety": "lo \u00e2u",
    "depression": "tr\u1ea7m c\u1ea3m",
    "nervousness": "h\u1ed3i h\u1ed9p",
    "confusion": "l\u00fa l\u1eabn",
    "hallucination": "\u1ea3o gi\u00e1c",
    "seizure": "co gi\u1eadt",
    "convulsion": "co gi\u1eadt",
    "tremor": "run",
    "rash": "ph\u00e1t ban",
    "hives": "m\u1ec1 \u0111ay",
    "blister": "m\u1ee5n n\u01b0\u1edbc",
    "dry skin": "da kh\u00f4",
    "dry mouth": "kh\u00f4 mi\u1ec7ng",
    "mouth ulcers": "lo\u00e9t mi\u1ec7ng",
    "hair loss": "r\u1ee5ng t\u00f3c",
    "muscle pain": "\u0111au c\u01a1",
    "joint pain": "\u0111au kh\u1edbp",
    "back pain": "\u0111au l\u01b0ng",
    "chest pain": "\u0111au ng\u1ef1c",
    "abdominal pain": "\u0111au b\u1ee5ng",
    "shortness of breath": "kh\u00f3 th\u1edf",
    "difficulty breathing": "kh\u00f3 th\u1edf",
    "wheezing": "th\u1edf kh\u00f2 kh\u00e8",
    "palpitations": "h\u1ed3i h\u1ed9p",
    "rapid heart rate": "nh\u1ecbp tim nhanh",
    "slow heart rate": "nh\u1ecbp tim ch\u1eadm",
    "irregular heartbeat": "lo\u1ea1n nh\u1ecbp tim",
    "high blood pressure": "t\u0103ng huy\u1ebft \u00e1p",
    "low blood pressure": "h\u1ea1 huy\u1ebft \u00e1p",
    "edema": "ph\u00f9",
    "swollen": "s\u01b0ng",
    "numbness": "t\u00ea",
    "tingling": "kim ch\u00e2m",
    "vision changes": "thay \u0111\u1ed5i th\u1ecb l\u1ef1c",
    "blurred vision": "m\u1edd m\u1eaft",
    "double vision": "song th\u1ecb",
    "eye pain": "\u0111au m\u1eaft",
    "ear pain": "\u0111au tai",
    "ringing in ears": "\u00f9 tai",
    "hearing loss": "m\u1ea5t th\u00ednh l\u1ef1c",

    # Body parts
    "head": "\u0111\u1ea7u",
    "eye": "m\u1eaft",
    "eyes": "m\u1eaft",
    "ear": "tai",
    "ears": "tai",
    "nose": "m\u0169i",
    "throat": "h\u1ecdng",
    "mouth": "mi\u1ec7ng",
    "tongue": "l\u01b0\u1ee1i",
    "lip": "m\u00f4i",
    "lips": "m\u00f4i",
    "tooth": "r\u0103ng",
    "teeth": "r\u0103ng",
    "gum": "l\u1ee3i",
    "gums": "l\u1ee3i",
    "neck": "c\u1ed5",
    "shoulder": "vai",
    "chest": "ng\u1ef1c",
    "back": "l\u01b0ng",
    "abdomen": "b\u1ee5ng",
    "stomach": "d\u1ea1 d\u00e0y",
    "intestine": "ru\u1ed9t",
    "liver": "gan",
    "kidney": "th\u1eadn",
    "kidneys": "th\u1eadn",
    "lung": "ph\u1ed5i",
    "lungs": "ph\u1ed5i",
    "heart": "tim",
    "brain": "n\u00e3o",
    "nerve": "th\u1ea7n kinh",
    "nerves": "th\u1ea7n kinh",
    "bone": "x\u01b0\u01a1ng",
    "bones": "x\u01b0\u01a1ng",
    "joint": "kh\u1edbp",
    "joints": "kh\u1edbp",
    "muscle": "c\u01a1",
    "muscles": "c\u01a1",
    "skin": "da",
    "blood": "m\u00e1u",
    "urine": "n\u01b0\u1edbc ti\u1ec3u",
    "stool": "ph\u00e2n",

    # Medical conditions
    "infection": "nhi\u1ec5m tr\u00f9ng",
    "bacterial infection": "nhi\u1ec5m tr\u00f9ng vi khu\u1ea9n",
    "viral infection": "nhi\u1ec5m virus",
    "fungal infection": "nhi\u1ec5m n\u1ea5m",
    "allergic reaction": "ph\u1ea3n \u1ee9ng d\u1ecb \u1ee9ng",
    "allergy": "d\u1ecb \u1ee9ng",
    "asthma": "hen suy\u1ec5n",
    "diabetes": "\u0111\u00e1i th\u00e1o \u0111\u01b0\u1eddng",
    "type 1 diabetes": "\u0111\u00e1i th\u00e1o \u0111\u01b0\u1eddng type 1",
    "type 2 diabetes": "\u0111\u00e1i th\u00e1o \u0111\u01b0\u1eddng type 2",
    "hypertension": "t\u0103ng huy\u1ebft \u00e1p",
    "hypotension": "h\u1ea1 huy\u1ebft \u00e1p",
    "heart disease": "b\u1ec7nh tim",
    "heart failure": "suy tim",
    "stroke": "\u0111\u1ed9t qu\u1ef5",
    "arthritis": "vi\u00eam kh\u1edbp",
    "osteoarthritis": "vi\u00eam x\u01b0\u01a1ng kh\u1edbp",
    "osteoporosis": "lo\u00e3ng x\u01b0\u01a1ng",
    "cancer": "ung th\u01b0",
    "tumor": "kh\u1ed1i u",
    "ulcer": "lo\u00e9t",
    "gastric ulcer": "lo\u00e9t d\u1ea1 d\u00e0y",
    "inflammation": "vi\u00eam",
    "swelling": "s\u01b0ng",
    "fracture": "g\u00e3y x\u01b0\u01a1ng",
    "wound": "v\u1ebft th\u01b0\u01a1ng",
    "burn": "b\u1ecfng",
    "cut": "v\u1ebft c\u1eaft",
    "scar": "s\u1eb9o",

    # Medical actions
    "treatment": "\u0111i\u1ec1u tr\u1ecb",
    "prevention": "ph\u00f2ng ng\u1eeba",
    "diagnosis": "ch\u1ea9n \u0111o\u00e1n",
    "relief": "gi\u1ea3m nh\u1eb9",
    "relieve": "l\u00e0m gi\u1ea3m",
    "reduce": "gi\u1ea3m",
    "prevent": "ng\u0103n ng\u1eeba",
    "control": "ki\u1ec3m so\u00e1t",
    "manage": "qu\u1ea3n l\u00fd",
    "improve": "c\u1ea3i thi\u1ec7n",
    "promote": "th\u00fac \u0111\u1ea9y",
    "protect": "b\u1ea3o v\u1ec7",
    "clean": "l\u00e0m s\u1ea1ch",
    "disinfect": "kh\u1eed tr\u00f9ng",
    "moisten": "l\u00e0m \u1ea9m",
    "soothe": "l\u00e0m d\u1ecbu",
    "heal": "l\u00e0m l\u00e0nh",
    "cool": "l\u00e0m m\u00e1t",
    "warm": "l\u00e0m \u1ea5m",

    # Dosage / administration
    "take by mouth": "u\u1ed1ng",
    "take orally": "u\u1ed1ng",
    "oral administration": "\u0111\u01b0\u1eddng u\u1ed1ng",
    "apply to skin": "b\u00f4i ngo\u00e0i da",
    "topical application": "b\u00f4i t\u1ea1i ch\u1ed7",
    "inject": "ti\u00eam",
    "intravenous": "ti\u00eam t\u0129nh m\u1ea1ch",
    "intramuscular": "ti\u00eam b\u1eafp",
    "subcutaneous": "ti\u00eam d\u01b0\u1edbi da",
    "inhale": "h\u00edt",
    "apply to eye": "nh\u1ecf m\u1eaft",
    "apply to ear": "nh\u1ecf tai",
    "apply to nose": "nh\u1ecf m\u0169i",
    "rectal": "\u0111\u01b0\u1eddng tr\u1ef1c tr\u00e0ng",
    "vaginal": "\u0111\u01b0\u1eddng \u00e2m \u0111\u1ea1o",
    "with food": "c\u00f9ng v\u1edbi th\u1ee9c \u0103n",
    "after meals": "sau khi \u0103n",
    "before meals": "tr\u01b0\u1edbc khi \u0103n",
    "on empty stomach": "l\u00fac \u0111\u00f3i",
    "with plenty of water": "v\u1edbi nhi\u1ec1u n\u01b0\u1edbc",
    "as directed": "theo ch\u1ec9 d\u1eabn",
    "as needed": "khi c\u1ea7n",
    "every day": "m\u1ed7i ng\u00e0y",
    "daily": "h\u1eb1ng ng\u00e0y",
    "once a day": "ng\u00e0y m\u1ed9t l\u1ea7n",
    "twice a day": "ng\u00e0y hai l\u1ea7n",
    "three times a day": "ng\u00e0y ba l\u1ea7n",
    "four times a day": "ng\u00e0y b\u1ed1n l\u1ea7n",
    "every 4 hours": "m\u1ed7i 4 gi\u1edd",
    "every 6 hours": "m\u1ed7i 6 gi\u1edd",
    "every 8 hours": "m\u1ed7i 8 gi\u1edd",
    "every 12 hours": "m\u1ed7i 12 gi\u1edd",
    "at bedtime": "tr\u01b0\u1edbc khi ng\u1ee7",
    "in the morning": "v\u00e0o bu\u1ed5i s\u00e1ng",
    "in the evening": "v\u00e0o bu\u1ed5i t\u1ed1i",
    "maximum": "t\u1ed1i \u0111a",
    "minimum": "t\u1ed1i thi\u1ec3u",
    "do not exceed": "kh\u00f4ng v\u01b0\u1ee3t qu\u00e1",
    "do not take": "kh\u00f4ng \u0111\u01b0\u1ee3c d\u00f9ng",
    "do not use": "kh\u00f4ng \u0111\u01b0\u1ee3c d\u00f9ng",
    "consult a doctor": "tham kh\u1ea3o \u00fd ki\u1ebfn b\u00e1c s\u0129",
    "ask your doctor": "h\u1ecfi \u00fd ki\u1ebfn b\u00e1c s\u0129",
    "under medical supervision": "d\u01b0\u1edbi s\u1ef1 gi\u00e1m s\u00e1t y t\u1ebf",
    "prescription": "theo \u0111\u01a1n",
    "prescription only": "thu\u1ed1c k\u00ea \u0111\u01a1n",
    "over the counter": "thu\u1ed1c kh\u00f4ng k\u00ea \u0111\u01a1n",
    "otc": "kh\u00f4ng k\u00ea \u0111\u01a1n",

    # Measurement units
    "mg": "mg",
    "mcg": "mcg",
    "g": "g",
    "ml": "ml",
    "l": "l",
    "tablet": "vi\u00ean",
    "tablets": "vi\u00ean",
    "capsule": "vi\u00ean nang",
    "capsules": "vi\u00ean nang",
    "drop": "gi\u1ecdt",
    "drops": "gi\u1ecdt",
    "spray": "l\u1ea7n x\u1ecbt",
    "puff": "l\u1ea7n h\u00edt",
    "inhalation": "l\u1ea7n h\u00edt",
    "application": "l\u1ea7n b\u00f4i",
    "dose": "li\u1ec1u",
    "doses": "li\u1ec1u",
    "dosage": "li\u1ec1u l\u01b0\u1ee3ng",
    "milligram": "miligam",
    "microgram": "microgam",
    "milliliter": "milil\u00edt",

    # Common verbs
    "may cause": "c\u00f3 th\u1ec3 g\u00e2y",
    "may occur": "c\u00f3 th\u1ec3 x\u1ea3y ra",
    "may include": "c\u00f3 th\u1ec3 bao g\u1ed3m",
    "including": "bao g\u1ed3m",
    "such as": "nh\u01b0",
    "for example": "v\u00ed d\u1ee5",
    "common": "th\u01b0\u1eddng g\u1eb7p",
    "uncommon": "\u00edt g\u1eb7p",
    "rare": "hi\u1ebfm g\u1eb7p",
    "serious": "nghi\u00eam tr\u1ecdng",
    "severe": "nghi\u00eam tr\u1ecdng",
    "mild": "nh\u1eb9",
    "moderate": "trung b\u00ecnh",
    "severe": "n\u1eb7ng",
    "temporary": "t\u1ea1m th\u1eddi",
    "permanent": "v\u0129nh vi\u1ec5n",
    "chronic": "m\u00e3n t\u00ednh",
    "acute": "c\u1ea5p t\u00ednh",
    "sudden": "\u0111\u1ed9t ng\u1ed9t",
    "gradual": "t\u1eeb t\u1eeb",
    "immediate": "ngay l\u1eadp t\u1ee9c",
    "immediately": "ngay l\u1eadp t\u1ee9c",
    "urgent": "kh\u1ea9n c\u1ea5p",
    "emergency": "c\u1ea5p c\u1ee9u",
    "recommended": "khuy\u1ebfn c\u00e1o",
    "suggested": "\u0111\u1ec1 ngh\u1ecb",
    "required": "y\u00eau c\u1ea7u",
    "necessary": "c\u1ea7n thi\u1ebft",
    "possible": "c\u00f3 th\u1ec3",
    "likely": "c\u00f3 kh\u1ea3 n\u0103ng",
    "unlikely": "kh\u00f4ng ch\u1eafc",
    "avoid": "tr\u00e1nh",
    "stop": "ng\u1eebng",
    "continue": "ti\u1ebfp t\u1ee5c",
    "start": "b\u1eaft \u0111\u1ea7u",
    "increase": "t\u0103ng",
    "decrease": "gi\u1ea3m",
    "report": "b\u00e1o c\u00e1o",
    "contact": "li\u00ean h\u1ec7",
    "seek medical attention": "\u0111\u1ebfn c\u01a1 s\u1edf y t\u1ebf",

    # Contraindication / warning
    "contraindicated": "ch\u1ed1ng ch\u1ecb \u0111\u1ecbnh",
    "contraindications": "ch\u1ed1ng ch\u1ecb \u0111\u1ecbnh",
    "warning": "c\u1ea3nh b\u00e1o",
    "warnings": "c\u1ea3nh b\u00e1o",
    "precaution": "th\u1eadn tr\u1ecdng",
    "precautions": "th\u1eadn tr\u1ecdng",
    "side effects": "t\u00e1c d\u1ee5ng ph\u1ee5",
    "adverse reaction": "ph\u1ea3n \u1ee9ng b\u1ea5t l\u1ee3i",
    "adverse reactions": "ph\u1ea3n \u1ee9ng b\u1ea5t l\u1ee3i",
    "allergic": "d\u1ecb \u1ee9ng",
    "hypersensitivity": "qu\u00e1 m\u1eabn",
    "overdose": "qu\u00e1 li\u1ec1u",
    "poisoning": "ng\u1ed9 \u0111\u1ed9c",
    "pregnancy": "mang thai",
    "pregnant": "c\u00f3 thai",
    "breastfeeding": "cho con b\u00fa",
    "lactation": "cho con b\u00fa",
    "children": "tr\u1ebb em",
    "infants": "tr\u1ebb s\u01a1 sinh",
    "elderly": "ng\u01b0\u1eddi cao tu\u1ed5i",
    "geriatric": "ng\u01b0\u1eddi gi\u00e0",
    "pediatric": "nhi khoa",
    "adult": "ng\u01b0\u1eddi l\u1edbn",
    "driving": "l\u00e1i xe",
    "operate machinery": "v\u1eadn h\u00e0nh m\u00e1y m\u00f3c",
    "alcohol": "r\u01b0\u1ee3u bia",
    "grapefruit": "b\u01b0\u1edfi",
    "drowsy": "bu\u1ed3n ng\u1ee7",
    "drowsiness": "bu\u1ed3n ng\u1ee7",
    "dizziness": "ch\u00f3ng m\u1eb7t",
    "kidney disease": "b\u1ec7nh th\u1eadn",
    "liver disease": "b\u1ec7nh gan",
    "heart disease": "b\u1ec7nh tim",
    "thyroid disease": "b\u1ec7nh tuy\u1ebfn gi\u00e1p",
    "asthma": "hen suy\u1ec5n",
    "diabetes": "\u0111\u00e1i th\u00e1o \u0111\u01b0\u1eddng",
    "glaucoma": "gl\u00f4c\u00f4m",
    "seizure": "co gi\u1eadt",
    "epilepsy": "\u0111\u1ed9ng kinh",
    "bleeding disorder": "r\u1ed1i lo\u1ea1n ch\u1ea3y m\u00e1u",
    "blood clot": "c\u1ee5c m\u00e1u \u0111\u00f4ng",
    "surgery": "ph\u1eabu thu\u1eadt",
    "operation": "ph\u1eabu thu\u1eadt",
    "dental procedure": "th\u1ee7 thu\u1eadt nha khoa",
    "drug interaction": "t\u01b0\u01a1ng t\u00e1c thu\u1ed1c",
    "interaction": "t\u01b0\u01a1ng t\u00e1c",
    "maoi": "MAOI",
    "ssri": "SSRI",
    "nsaid": "NSAID",
    "anticoagulant": "thu\u1ed1c ch\u1ed1ng \u0111\u00f4ng",
    "blood thinner": "thu\u1ed1c lo\u00e3ng m\u00e1u",
    "diuretic": "thu\u1ed1c l\u1ee3i ti\u1ec3u",
    "beta blocker": "thu\u1ed1c ch\u1eb9n beta",
    "ace inhibitor": "thu\u1ed1c \u1ee9c ch\u1ebf ACE",
    "statin": "thu\u1ed1c statin",

    # Directions
    "direction": "h\u01b0\u1edbng d\u1eabn",
    "directions": "h\u01b0\u1edbng d\u1eabn",
    "usage": "c\u00e1ch d\u00f9ng",
    "uses": "c\u00f4ng d\u1ee5ng",
    "indication": "ch\u1ec9 \u0111\u1ecbnh",
    "indications": "ch\u1ec9 \u0111\u1ecbnh",
    "information": "th\u00f4ng tin",
    "description": "m\u00f4 t\u1ea3",
    "ingredients": "th\u00e0nh ph\u1ea7n",
    "active ingredient": "th\u00e0nh ph\u1ea7n ho\u1ea1t ch\u1ea5t",
    "inactive ingredients": "t\u00e1 d\u01b0\u1ee3c",

    # Remaining untranslated English words
    "aches": "\u0111au nh\u1ee9c",
    "ache": "\u0111au",
    "aching": "\u0111au",
    "painful": "\u0111au \u0111\u1edbn",
    "pains": "\u0111au",
    "muscular": "c\u01a1 b\u1eafp",
    "symptoms": "tri\u1ec7u ch\u1ee9ng",
    "symptom": "tri\u1ec7u ch\u1ee9ng",
    "provider": "nh\u00e0 cung c\u1ea5p",
    "product": "s\u1ea3n ph\u1ea9m",
    "doctor": "b\u00e1c s\u0129",
    "physician": "b\u00e1c s\u0129",
    "patient": "b\u1ec7nh nh\u00e2n",
    "patients": "b\u1ec7nh nh\u00e2n",
    "minor": "nh\u1eb9",
    "fast": "nhanh",
    "quick": "nhanh",
    "rapid": "nhanh",
    "slow": "ch\u1eadm",
    "slowly": "t\u1eeb t\u1eeb",
    "delayed": "ch\u1eadm",
    "immediate": "ngay l\u1eadp t\u1ee9c",
    "immediately": "ngay l\u1eadp t\u1ee9c",
    "cold": "c\u1ea3m l\u1ea1nh",
    "colds": "c\u1ea3m l\u1ea1nh",
    "menstrual": "kinh nguy\u1ec7t",
    "arthritis": "vi\u00eam kh\u1edbp",
    "temporarily": "t\u1ea1m th\u1eddi",
    "effectiveness": "hi\u1ec7u qu\u1ea3",
    "effective": "hi\u1ec7u qu\u1ea3",
    "provide": "cung c\u1ea5p",
    "help": "gi\u00fap",
    "helps": "gi\u00fap",
    "prevent": "ng\u0103n ng\u1eeba",
    "prevents": "ng\u0103n ng\u1eeba",
    "prevention": "ph\u00f2ng ng\u1eeba",
    "protect": "b\u1ea3o v\u1ec7",
    "protects": "b\u1ea3o v\u1ec7",
    "reduce": "gi\u1ea3m",
    "reduces": "gi\u1ea3m",
    "reducing": "gi\u1ea3m",
    "increased": "t\u0103ng",
    "increasing": "t\u0103ng",
    "decreased": "gi\u1ea3m",
    "decreasing": "gi\u1ea3m",
    "development": "ph\u00e1t tri\u1ec3n",
    "maintain": "duy tr\u00ec",
    "maintains": "duy tr\u00ec",
    "maintenance": "duy tr\u00ec",
    "resistant": "kh\u00e1ng thu\u1ed1c",
    "resistance": "kh\u00e1ng thu\u1ed1c",
    "bacterial": "vi khu\u1ea9n",
    "bacteria": "vi khu\u1ea9n",
    "virus": "virus",
    "viral": "virus",
    "fungus": "n\u1ea5m",
    "fungal": "n\u1ea5m",
    "microbial": "vi sinh",
    "germs": "vi tr\u00f9ng",
    "infection": "nhi\u1ec5m tr\u00f9ng",
    "infections": "nhi\u1ec5m tr\u00f9ng",
    "infected": "b\u1ecb nhi\u1ec5m",
    "contamination": "\u00f4 nhi\u1ec5m",
    "contaminated": "\u00f4 nhi\u1ec5m",
    "wound": "v\u1ebft th\u01b0\u01a1ng",
    "wounds": "v\u1ebft th\u01b0\u01a1ng",
    "injury": "ch\u1ea5n th\u01b0\u01a1ng",
    "injuries": "ch\u1ea5n th\u01b0\u01a1ng",
    "sore": "\u0111au",
    "sores": "v\u1ebft lo\u00e9t",
    "ulcer": "lo\u00e9t",
    "ulcers": "lo\u00e9t",
    "lesion": "t\u1ed5n th\u01b0\u01a1ng",
    "lesions": "t\u1ed5n th\u01b0\u01a1ng",
    "tissue": "m\u00f4",
    "tissues": "m\u00f4",
    "fluid": "d\u1ecbch",
    "fluids": "d\u1ecbch",
    "mucus": "ch\u1ea5t nh\u1ea7y",
    "phlegm": "\u0111\u1eddm",
    "sputum": "\u0111\u1eddm",
    "blood": "m\u00e1u",
    "bleeding": "ch\u1ea3y m\u00e1u",
    "hemorrhage": "xu\u1ea5t huy\u1ebft",
    "clot": "\u0111\u00f4ng m\u00e1u",
    "clotting": "\u0111\u00f4ng m\u00e1u",
    "pressure": "\u00e1p l\u1ef1c",
    "blood pressure": "huy\u1ebft \u00e1p",
    "blood glucose": "\u0111\u01b0\u1eddng huy\u1ebft",
    "glucose": "\u0111\u01b0\u1eddng",
    "sugar": "\u0111\u01b0\u1eddng",
    "cholesterol": "cholesterol",
    "lipid": "m\u1ee1 m\u00e1u",
    "lipids": "m\u1ee1 m\u00e1u",
    "triglyceride": "triglycerid",
    "enzyme": "enzym",
    "enzymes": "enzym",
    "protein": "protein",
    "proteins": "protein",
    "hormone": "hormone",
    "hormones": "hormone",
    "cell": "t\u1ebf b\u00e0o",
    "cells": "t\u1ebf b\u00e0o",
    "cellular": "t\u1ebf b\u00e0o",
    "immune": "mi\u1ec5n d\u1ecbch",
    "immunity": "mi\u1ec5n d\u1ecbch",
    "system": "h\u1ec7 th\u1ed1ng",
    "systems": "h\u1ec7 th\u1ed1ng",
    "body": "c\u01a1 th\u1ec3",
    "general": "t\u1ed5ng qu\u00e1t",
    "specific": "c\u1ee5 th\u1ec3",
    "regular": "\u0111\u1ec1u \u0111\u1eb7n",
    "regularly": "\u0111\u1ec1u \u0111\u1eb7n",
    "proper": "\u0111\u00fang c\u00e1ch",
    "properly": "\u0111\u00fang c\u00e1ch",
    "carefully": "c\u1ea9n th\u1eadn",
    "caution": "th\u1eadn tr\u1ecdng",
    "careful": "c\u1ea9n th\u1eadn",
    "important": "quan tr\u1ecdng",
    "necessary": "c\u1ea7n thi\u1ebft",
    "essential": "thi\u1ebft y\u1ebfu",
    "appropriate": "th\u00edch h\u1ee3p",
    "adequate": "\u0111\u1ea7y \u0111\u1ee7",
    "sufficient": "\u0111\u1ee7",
    "excessive": "qu\u00e1 m\u1ee9c",
    "excess": "d\u01b0 th\u1eeba",
    "additional": "b\u1ed5 sung",
    "extra": "th\u00eam",
    "further": "th\u00eam",
    "possible": "c\u00f3 th\u1ec3",
    "potential": "ti\u1ec1m \u1ea9n",
    "potentially": "c\u00f3 th\u1ec3",
    "primary": "ch\u00ednh",
    "secondary": "th\u1ee9 ph\u00e1t",
    "initial": "ban \u0111\u1ea7u",
    "early": "s\u1edbm",
    "late": "mu\u1ed9n",
    "advanced": "ti\u1ebfn tri\u1ec3n",
    "progressive": "ti\u1ebfn tri\u1ec3n",
    "active": "ho\u1ea1t \u0111\u1ed9ng",
    "inactive": "kh\u00f4ng ho\u1ea1t \u0111\u1ed9ng",
    "normal": "b\u00ecnh th\u01b0\u1eddng",
    "abnormal": "b\u1ea5t th\u01b0\u1eddng",
    "elevated": "cao",
    "low": "th\u1ea5p",
    "high": "cao",
    "higher": "cao h\u01a1n",
    "lower": "th\u1ea5p h\u01a1n",
    "increased": "t\u0103ng",
    "reduced": "gi\u1ea3m",
    "significant": "\u0111\u00e1ng k\u1ec3",
    "significantly": "\u0111\u00e1ng k\u1ec3",
    "substantial": "\u0111\u00e1ng k\u1ec3",
    "slight": "nh\u1eb9",
    "slightly": "nh\u1eb9",
    "marked": "r\u00f5 r\u1ec7t",
    "notable": "\u0111\u00e1ng ch\u00fa \u00fd",
    "level": "m\u1ee9c",
    "levels": "m\u1ee9c",
    "rate": "t\u1ed1c \u0111\u1ed9",
    "rates": "t\u1ed1c \u0111\u1ed9",
    "amount": "l\u01b0\u1ee3ng",
    "number": "s\u1ed1",
    "frequency": "t\u1ea7n su\u1ea5t",
    "duration": "th\u1eddi gian",
    "period": "giai \u0111o\u1ea1n",
    "periods": "giai \u0111o\u1ea1n",
    "phase": "giai \u0111o\u1ea1n",
    "stage": "giai \u0111o\u1ea1n",
    "stages": "giai \u0111o\u1ea1n",
    "area": "v\u00f9ng",
    "areas": "v\u00f9ng",
    "site": "v\u1ecb tr\u00ed",
    "sites": "v\u1ecb tr\u00ed",
    "location": "v\u1ecb tr\u00ed",
    "surface": "b\u1ec1 m\u1eb7t",
    "layer": "l\u1edbp",
    "lining": "ni\u00eam m\u1ea1c",
    "membrane": "m\u00e0ng",
    "wall": "th\u00e0nh",
    "walls": "th\u00e0nh",
    "tube": "\u1ed1ng",
    "valve": "van",
    "valves": "van",
    "vessel": "m\u1ea1ch",
    "vessels": "m\u1ea1ch",
    "artery": "\u0111\u1ed9ng m\u1ea1ch",
    "arteries": "\u0111\u1ed9ng m\u1ea1ch",
    "vein": "t\u0129nh m\u1ea1ch",
    "veins": "t\u0129nh m\u1ea1ch",
    "capillary": "mao m\u1ea1ch",
    "capillaries": "mao m\u1ea1ch",
    "nerve": "th\u1ea7n kinh",
    "nerves": "th\u1ea7n kinh",
    "nerve fiber": "s\u1ee3i th\u1ea7n kinh",
    "neuron": "n\u01a1-ron",
    "neurons": "n\u01a1-ron",
    "nerve damage": "t\u1ed5n th\u01b0\u01a1ng th\u1ea7n kinh",
    "neuropathy": "b\u1ec7nh th\u1ea7n kinh",
    "neural": "th\u1ea7n kinh",
    "sensory": "c\u1ea3m gi\u00e1c",
    "motor": "v\u1eadn \u0111\u1ed9ng",
    "movement": "c\u1eed \u0111\u1ed9ng",
    "function": "ch\u1ee9c n\u0103ng",
    "functions": "ch\u1ee9c n\u0103ng",
    "functional": "ch\u1ee9c n\u0103ng",
    "activity": "ho\u1ea1t \u0111\u1ed9ng",
    "activities": "ho\u1ea1t \u0111\u1ed9ng",
    "process": "qu\u00e1 tr\u00ecnh",
    "processes": "qu\u00e1 tr\u00ecnh",
    "response": "\u0111\u00e1p \u1ee9ng",
    "responses": "\u0111\u00e1p \u1ee9ng",
    "reaction": "ph\u1ea3n \u1ee9ng",
    "reactions": "ph\u1ea3n \u1ee9ng",
    "effect": "t\u00e1c d\u1ee5ng",
    "effects": "t\u00e1c d\u1ee5ng",
    "affect": "\u1ea3nh h\u01b0\u1edfng",
    "affects": "\u1ea3nh h\u01b0\u1edfng",
    "affecting": "\u1ea3nh h\u01b0\u1edfng",
    "impact": "\u1ea3nh h\u01b0\u1edfng",
    "influence": "\u1ea3nh h\u01b0\u1edfng",
    "role": "vai tr\u00f2",
    "action": "t\u00e1c d\u1ee5ng",
    "actions": "t\u00e1c d\u1ee5ng",
    "mechanism": "c\u01a1 ch\u1ebf",
    "mechanisms": "c\u01a1 ch\u1ebf",
    "pathway": "con \u0111\u01b0\u1eddng",
    "pathways": "con \u0111\u01b0\u1eddng",
    "factor": "y\u1ebfu t\u1ed1",
    "factors": "y\u1ebfu t\u1ed1",
    "risk": "nguy c\u01a1",
    "risks": "nguy c\u01a1",
    "benefit": "l\u1ee3i \u00edch",
    "benefits": "l\u1ee3i \u00edch",
    "advantage": "\u01b0u \u0111i\u1ec3m",
    "disadvantage": "nh\u01b0\u1ee3c \u0111i\u1ec3m",
    "success": "th\u00e0nh c\u00f4ng",
    "successful": "th\u00e0nh c\u00f4ng",
    "failure": "th\u1ea5t b\u1ea1i",
    "outcome": "k\u1ebft qu\u1ea3",
    "outcomes": "k\u1ebft qu\u1ea3",
    "complication": "bi\u1ebfn ch\u1ee9ng",
    "complications": "bi\u1ebfn ch\u1ee9ng",
    "condition": "t\u00ecnh tr\u1ea1ng",
    "conditions": "t\u00ecnh tr\u1ea1ng",
    "disorder": "r\u1ed1i lo\u1ea1n",
    "disorders": "r\u1ed1i lo\u1ea1n",
    "disease": "b\u1ec7nh",
    "diseases": "b\u1ec7nh",
    "syndrome": "h\u1ed9i ch\u1ee9ng",
    "illness": "b\u1ec7nh",
    "illnesses": "b\u1ec7nh",
    "sickness": "\u1ed1m",
    "ailment": "b\u1ec7nh",
    "malady": "b\u1ec7nh",
    "malaria": "s\u1ed1t r\u00e9t",
    "tuberculosis": "lao",
    "pneumonia": "vi\u00eam ph\u1ed5i",
    "bronchitis": "vi\u00eam ph\u1ebf qu\u1ea3n",
    "sinusitis": "vi\u00eam xoang",
    "tonsillitis": "vi\u00eam amidan",
    "pharyngitis": "vi\u00eam h\u1ecdng",
    "laryngitis": "vi\u00eam thanh qu\u1ea3n",
    "otitis": "vi\u00eam tai",
    "conjunctivitis": "vi\u00eam k\u1ebft m\u1ea1c",
    "dermatitis": "vi\u00eam da",
    "eczema": "ch\u00e0m",
    "psoriasis": "v\u1ea3y n\u1ebfn",
    "acne": "m\u1ee5n tr\u1ee9ng c\u00e1",
    "cellulitis": "vi\u00eam m\u00f4 t\u1ebf b\u00e0o",
    "abscess": "\u00e1p xe",
    "ulcer": "lo\u00e9t",
    "gastritis": "vi\u00eam d\u1ea1 d\u00e0y",
    "colitis": "vi\u00eam \u0111\u1ea1i tr\u00e0ng",
    "enteritis": "vi\u00eam ru\u1ed9t",
    "pancreatitis": "vi\u00eam t\u1ee5y",
    "cholecystitis": "vi\u00eam t\u00fai m\u1eadt",
    "appendicitis": "vi\u00eam ru\u1ed9t th\u1eeba",
    "meningitis": "vi\u00eam m\u00e0ng n\u00e3o",
    "encephalitis": "vi\u00eam n\u00e3o",
    "myocarditis": "vi\u00eam c\u01a1 tim",
    "endocarditis": "vi\u00eam n\u1ed9i t\u00e2m m\u1ea1c",
    "pericarditis": "vi\u00eam m\u00e0ng ngo\u00e0i tim",
    "cystitis": "vi\u00eam b\u00e0ng quang",
    "nephritis": "vi\u00eam th\u1eadn",
    "hepatitis": "vi\u00eam gan",
    "cirrhosis": "x\u01a1 gan",
    "fibrosis": "x\u01a1 h\u00f3a",
    "sclerosis": "x\u01a1 c\u1ee9ng",
    "stenosis": "h\u1eb9p",
    "obstruction": "t\u1eafc ngh\u1ebdn",
    "blockage": "t\u1eafc ngh\u1ebdn",
    "occlusion": "t\u1eafc",
    "rupture": "v\u1ee1",
    "perforation": "th\u1ee7ng",
    "tear": "r\u00e1ch",
    "spasm": "co th\u1eaft",
    "spasms": "co th\u1eaft",
    "cramp": "chu\u1ed9t r\u00fat",
    "cramps": "chu\u1ed9t r\u00fat",
    "tension": "c\u0103ng th\u1eb3ng",
    "strain": "c\u0103ng",
    "sprain": "bong g\u00e2n",
    "fracture": "g\u00e3y x\u01b0\u01a1ng",
    "fractures": "g\u00e3y x\u01b0\u01a1ng",
    "dislocation": "tr\u1eadt kh\u1edbp",
    "deformity": "d\u1ecb d\u1ea1ng",
    "malformation": "d\u1ecb t\u1eadt",
    "congenital": "b\u1ea9m sinh",
    "hereditary": "di truy\u1ec1n",
    "genetic": "di truy\u1ec1n",
    "acquired": "m\u1eafc ph\u1ea3i",
    "idiopathic": "v\u00f4 c\u0103n",
    "primary": "nguy\u00ean ph\u00e1t",
    "secondary": "th\u1ee9 ph\u00e1t",
    "benign": "l\u00e0nh t\u00ednh",
    "malignant": "\u00e1c t\u00ednh",
    "metastatic": "di c\u0103n",
    "invasive": "x\u00e2m l\u1ea5n",
    "localized": "khu tr\u00fa",
    "systemic": "to\u00e0n th\u00e2n",
    "generalized": "to\u00e0n th\u00e2n",
    "widespread": "lan r\u1ed9ng",
    "diffuse": "lan to\u1ea3",
    "limited": "gi\u1edbi h\u1ea1n",
    "extensive": "r\u1ed9ng",
    "severe": "n\u1eb7ng",
    "mild": "nh\u1eb9",
    "moderate": "v\u1eeba",
    "critical": "nguy k\u1ecbch",
    "terminal": "giai \u0111o\u1ea1n cu\u1ed1i",
    "fatal": "t\u1eed vong",
    "death": "t\u1eed vong",
    "survival": "s\u1ed1ng s\u00f3t",
    "prognosis": "ti\u00ean l\u01b0\u1ee3ng",
    "recovery": "h\u1ed3i ph\u1ee5c",
    "remission": "thuy\u00ean gi\u1ea3m",
    "relapse": "t\u00e1i ph\u00e1t",
    "recurrence": "t\u00e1i ph\u00e1t",
    "recurrent": "t\u00e1i ph\u00e1t",
    "chronic": "m\u00e3n t\u00ednh",
    "acute": "c\u1ea5p t\u00ednh",
    "subacute": "b\u00e1n c\u1ea5p",
    "persistent": "k\u00e9o d\u00e0i",
    "intermittent": "t\u1eebng c\u01a1n",
    "continuous": "li\u00ean t\u1ee5c",
    "constant": "li\u00ean t\u1ee5c",
    "episodic": "t\u1eebng \u0111\u1ee3t",
    "paroxysmal": "k\u1ecbch ph\u00e1t",
    "nocturnal": "v\u1ec1 \u0111\u00eam",
    "diurnal": "ban ng\u00e0y",
    "seasonal": "theo m\u00f9a",
    "year-round": "quanh n\u0103m",
    "annual": "h\u00e0ng n\u0103m",
    "monthly": "h\u00e0ng th\u00e1ng",
    "weekly": "h\u00e0ng tu\u1ea7n",
    # Common English words
    "the": "",
    "a": "",
    "an": "",
    "is": "l\u00e0",
    "are": "l\u00e0",
    "be": "\u0111\u01b0\u1ee3c",
    "was": "\u0111\u00e3",
    "were": "\u0111\u00e3",
    "been": "\u0111\u00e3",
    "have": "c\u00f3",
    "has": "c\u00f3",
    "had": "\u0111\u00e3 c\u00f3",
    "do": "l\u00e0m",
    "does": "l\u00e0m",
    "did": "\u0111\u00e3",
    "can": "c\u00f3 th\u1ec3",
    "could": "c\u00f3 th\u1ec3",
    "will": "s\u1ebd",
    "would": "s\u1ebd",
    "should": "n\u00ean",
    "may": "c\u00f3 th\u1ec3",
    "might": "c\u00f3 th\u1ec3",
    "must": "ph\u1ea3i",
    "shall": "s\u1ebd",
    "need": "c\u1ea7n",
    "not": "kh\u00f4ng",
    "no": "kh\u00f4ng",
    "yes": "c\u00f3",
    "and": "v\u00e0",
    "or": "ho\u1eb7c",
    "but": "nh\u01b0ng",
    "if": "n\u1ebfu",
    "because": "b\u1edfi v\u00ec",
    "so": "v\u00ec v\u1eady",
    "therefore": "do \u0111\u00f3",
    "also": "c\u0169ng",
    "as": "nh\u01b0",
    "than": "h\u01a1n",
    "then": "sau \u0111\u00f3",
    "when": "khi",
    "where": "n\u01a1i",
    "what": "g\u00ec",
    "which": "m\u00e0",
    "who": "ng\u01b0\u1eddi",
    "whom": "ng\u01b0\u1eddi",
    "whose": "c\u1ee7a ai",
    "why": "t\u1ea1i sao",
    "how": "l\u00e0m th\u1ebf n\u00e0o",
    "here": "\u1edf \u0111\u00e2y",
    "there": "\u1edf \u0111\u00f3",
    "with": "v\u1edbi",
    "without": "kh\u00f4ng c\u00f3",
    "for": "cho",
    "to": "\u0111\u1ec3",
    "from": "t\u1eeb",
    "of": "c\u1ee7a",
    "in": "trong",
    "into": "v\u00e0o",
    "on": "tr\u00ean",
    "onto": "l\u00ean",
    "at": "t\u1ea1i",
    "by": "b\u1edfi",
    "with": "v\u1edbi",
    "about": "v\u1ec1",
    "across": "qua",
    "after": "sau",
    "before": "tr\u01b0\u1edbc",
    "between": "gi\u1eefa",
    "under": "d\u01b0\u1edbi",
    "over": "tr\u00ean",
    "through": "qua",
    "throughout": "su\u1ed1t",
    "during": "trong th\u1eddi gian",
    "within": "trong v\u00f2ng",
    "without": "kh\u00f4ng c\u00f3",
    "against": "ch\u1ed1ng l\u1ea1i",
    "including": "bao g\u1ed3m",
    "exclude": "lo\u1ea1i tr\u1eeb",
    "excluding": "kh\u00f4ng bao g\u1ed3m",
    "up": "l\u00ean",
    "down": "xu\u1ed1ng",
    "off": "t\u1eaft",
    "out": "ra ngo\u00e0i",
    "in": "trong",
    "all": "t\u1ea5t c\u1ea3",
    "each": "m\u1ed7i",
    "every": "m\u1ed7i",
    "some": "m\u1ed9t s\u1ed1",
    "any": "b\u1ea5t k\u1ef3",
    "many": "nhi\u1ec1u",
    "much": "nhi\u1ec1u",
    "few": "\u00edt",
    "several": "m\u1ed9t v\u00e0i",
    "most": "h\u1ea7u h\u1ebft",
    "more": "th\u00eam",
    "less": "\u00edt h\u01a1n",
    "other": "kh\u00e1c",
    "another": "kh\u00e1c",
    "same": "gi\u1ed1ng",
    "different": "kh\u00e1c",
    "such": "nh\u01b0 v\u1eady",
    "only": "ch\u1ec9",
    "just": "ch\u1ec9",
    "very": "r\u1ea5t",
    "too": "c\u0169ng",
    "also": "c\u0169ng",
    "well": "t\u1ed1t",
    "now": "b\u00e2y gi\u1edd",
    "then": "sau \u0111\u00f3",
    "here": "\u1edf \u0111\u00e2y",
    "there": "\u1edf \u0111\u00f3",
    "your": "c\u1ee7a b\u1ea1n",
    "my": "c\u1ee7a t\u00f4i",
    "our": "c\u1ee7a ch\u00fang t\u00f4i",
    "his": "c\u1ee7a anh \u1ea5y",
    "her": "c\u1ee7a c\u00f4 \u1ea5y",
    "its": "c\u1ee7a n\u00f3",
    "their": "c\u1ee7a h\u1ecd",
    "your": "c\u1ee7a b\u1ea1n",
    "you": "b\u1ea1n",
    "we": "ch\u00fang t\u00f4i",
    "they": "h\u1ecd",
    "he": "anh \u1ea5y",
    "she": "c\u00f4 \u1ea5y",
    "it": "n\u00f3",
    "i": "t\u00f4i",
    "me": "t\u00f4i",
    "him": "anh \u1ea5y",
    "them": "h\u1ecd",
    "us": "ch\u00fang t\u00f4i",
    "this": "n\u00e0y",
    "that": "\u0111\u00f3",
    "these": "nh\u1eefng...n\u00e0y",
    "those": "nh\u1eefng...\u0111\u00f3",
    "due": "do",
    "because of": "b\u1edfi v\u00ec",
    "due to": "do",
    "result": "k\u1ebft qu\u1ea3",
    "resulting": "d\u1eabn \u0111\u1ebfn",
    "leading": "d\u1eabn \u0111\u1ebfn",
    "caused by": "g\u00e2y ra b\u1edfi",
    "causing": "g\u00e2y ra",
    "cause": "nguy\u00ean nh\u00e2n",
    "associated": "li\u00ean quan",
    "related": "li\u00ean quan",
    "following": "sau",
    "previous": "tr\u01b0\u1edbc \u0111\u00e2y",
    "prior": "tr\u01b0\u1edbc",
    "after": "sau",
    "before": "tr\u01b0\u1edbc",
    "during": "trong th\u1eddi gian",
    "while": "trong khi",
    "until": "cho \u0111\u1ebfn khi",
    "since": "t\u1eeb khi",
    "against": "ch\u1ed1ng",
    "around": "xung quanh",
    "away": "xa",
    "back": "tr\u1edf l\u1ea1i",
    "beside": "b\u00ean c\u1ea1nh",
    "beyond": "v\u01b0\u1ee3t qu\u00e1",
    "close": "g\u1ea7n",
    "far": "xa",
    "inside": "b\u00ean trong",
    "outside": "b\u00ean ngo\u00e0i",
    "near": "g\u1ea7n",
    "next": "ti\u1ebfp theo",
    "still": "v\u1eabn",
    "always": "lu\u00f4n lu\u00f4n",
    "never": "kh\u00f4ng bao gi\u1edd",
    "often": "th\u01b0\u1eddng",
    "sometimes": "\u0111\u00f4i khi",
    "usually": "th\u01b0\u1eddng",
    "generally": "n\u00f3i chung",
    "typically": "\u0111i\u1ec3n h\u00ecnh",
    "rarely": "hi\u1ebfm khi",
    "frequently": "th\u01b0\u1eddng xuy\u00ean",
    "especially": "\u0111\u1eb7c bi\u1ec7t",
    "particularly": "\u0111\u1eb7c bi\u1ec7t",
    "mainly": "ch\u1ee7 y\u1ebfu",
    "mostly": "ch\u1ee7 y\u1ebfu",
    "primarily": "ch\u1ee7 y\u1ebfu",
    "both": "c\u1ea3 hai",
    "either": "m\u1ed9t trong hai",
    "neither": "kh\u00f4ng c\u00e1i n\u00e0o",
    "whether": "li\u1ec7u",
    "although": "m\u1eb7c d\u00f9",
    "though": "m\u1eb7c d\u00f9",
    "however": "tuy nhi\u00ean",
    "instead": "thay v\u00e0o \u0111\u00f3",
    "rather": "thay v\u00ec",
    "than": "h\u01a1n",
    "always": "lu\u00f4n",
    "too": "qu\u00e1",
    "enough": "\u0111\u1ee7",
    "actually": "th\u1ef1c ra",
    "also": "c\u0169ng",
    "almost": "h\u1ea7u nh\u01b0",
    "already": "\u0111\u00e3",
    "yet": "ch\u01b0a",
    "still": "v\u1eabn",
    "again": "l\u1ea1i",
    "once": "m\u1ed9t l\u1ea7n",
    "twice": "hai l\u1ea7n",
    "about": "kho\u1ea3ng",
    "above": "tr\u00ean",
    "below": "d\u01b0\u1edbi",
    "moreover": "h\u01a1n n\u1eefa",
    "furthermore": "h\u01a1n n\u1eefa",
    "meanwhile": "trong khi \u0111\u00f3",
    "otherwise": "n\u1ebfu kh\u00f4ng",
    "therefore": "do \u0111\u00f3",
    "thus": "nh\u01b0 v\u1eady",
    "hence": "do \u0111\u00f3",
    "like": "nh\u01b0",
    "unlike": "kh\u00f4ng gi\u1ed1ng",
    "along": "d\u1ecdc theo",
    "among": "gi\u1eefa",
    "amid": "gi\u1eefa",
    "despite": "m\u1eb7c d\u00f9",
    "regardless": "b\u1ea5t k\u1ec3",
    "except": "ngo\u1ea1i tr\u1eeb",
    "besides": "b\u00ean c\u1ea1nh \u0111\u00f3",
    "regarding": "v\u1ec1",
    "concerning": "v\u1ec1",
    "according": "theo",
    "depending": "t\u00f9y thu\u1ed9c",
    "regardless of": "b\u1ea5t k\u1ec3",
    "unless": "tr\u1eeb khi",
    "provided": "v\u1edbi \u0111i\u1ec1u ki\u1ec7n",
    "through": "qua",
    "via": "th\u00f4ng qua",
    "per": "m\u1ed7i",
    "until": "cho \u0111\u1ebfn",
    "toward": "v\u1ec1 ph\u00eda",
    "towards": "v\u1ec1 ph\u00eda",
    "upon": "tr\u00ean",
    "via": "qua",
    "whereas": "trong khi",
    "wherever": "b\u1ea5t c\u1ee9 n\u01a1i \u0111\u00e2u",
    "whatever": "b\u1ea5t c\u1ee9 \u0111i\u1ec1u g\u00ec",
    "whoever": "b\u1ea5t c\u1ee9 ai",
    "\u2013": "-",
    "\u2014": "-",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": "\"",
    "\u201d": "\"",
    "\u2022": "*",
    "\u2026": "...",
}

MEDICAL_PATTERNS = sorted(MEDICAL_DICT.items(), key=lambda x: -len(x[0]))


def translate_text(text: str) -> str:
    if not text:
        return ""
    # Normalize whitespace and punctuation spacing
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'([.,!?;:()\[\]{}])', r' \1 ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    # Apply phrase replacements (longest first)
    for eng, vie in MEDICAL_PATTERNS:
        pattern = re.compile(r'\b' + re.escape(eng) + r'\b', re.IGNORECASE)
        if vie == "":
            text = pattern.sub("", text)
        else:
            text = pattern.sub(vie, text)
    # Handle words with trailing 's' or 'es' (plurals/verbs)
    # Build reverse lookup from MEDICAL_DICT
    med_dict_lower = {k.lower(): v for k, v in MEDICAL_DICT.items()}
    words = text.split()
    translated_words = []
    for word in words:
        word_lower = word.lower()
        if word_lower in med_dict_lower:
            translated_words.append(med_dict_lower[word_lower])
        else:
            # Try stripping trailing 's' or 'es'
            stripped = word_lower
            if stripped.endswith('ies') and len(stripped) > 4:
                stripped = stripped[:-3] + 'y'
            elif stripped.endswith('es') and len(stripped) > 4:
                stripped = stripped[:-2]
            elif stripped.endswith('s') and len(stripped) > 3 and not stripped.endswith('ss'):
                stripped = stripped[:-1]
            if stripped != word_lower and stripped in med_dict_lower:
                translated_words.append(med_dict_lower[stripped])
            else:
                # Try compound splitting for common patterns
                # e.g., backache -> back + ache, toothache -> tooth + ache, headache -> head + ache
                compound_parts = ['head', 'back', 'tooth', 'ear', 'eye', 'stomach', 'muscle', 'chest', 'neck', 'joint']
                for part in compound_parts:
                    if word_lower.endswith(part + 'ache'):
                        ache_part = word_lower[:-4]  # remove 'ache'
                        part_vn = med_dict_lower.get(part, part)
                        ache_vn = med_dict_lower.get('ache', 'ache')
                        if ache_part and ache_part in med_dict_lower:
                            translated_words.append(ache_vn + ' ' + med_dict_lower[ache_part])
                        else:
                            translated_words.append(ache_vn + ' ' + part_vn)
                        break
                    elif word_lower.endswith('ache'):
                        # simple ache compound
                        base = word_lower[:-4]
                        if base in med_dict_lower:
                            translated_words.append('đau ' + med_dict_lower[base])
                            break
                else:
                    translated_words.append(word)
    text = ' '.join(translated_words)
    # Clean up extra spaces and fix punctuation
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'\s+([.,!?;:])', r'\1', text)
    text = re.sub(r'([([])\s+', r'\1', text)
    text = re.sub(r'\s+([)\]])\s*', r'\1 ', text)
    text = text.strip()
    return text


def translate_manufacturer(name: str) -> str:
    """Translate manufacturer suffix to Vietnamese."""
    name = name.strip()
    replacements = [
        (r'\b(Inc|Corp|Incorporated|Corporation|Company|Co|Llc|Ltd|Limited|Pharmaceuticals?|Laboratories?|Biosciences?|Therapeutics?|Holdings?|Group|Plc|Gmbh)\b', '', True),
        (r',\s*$', '', False),
    ]
    for pattern, replacement, is_regex in replacements:
        if is_regex:
            name = re.sub(pattern, replacement, name, flags=re.IGNORECASE).strip()
        else:
            name = re.sub(pattern, replacement, name).strip()
    name = re.sub(r'\s+', ' ', name).strip()
    # Map known names
    name_map = {
        "P & L Development": "P & L Development",
        "Pharmadel": "Pharmadel",
        "Chain Drug Consortium": "Hi\u1ec7p h\u1ed9i D\u01b0\u1ee3c",
        "Amerisource Bergen": "Amerisource Bergen",
        "Cardinal Health": "Cardinal Health",
        "McKesson": "McKesson",
        "Solco Healthcare Us": "Solco Healthcare",
        "Dr. Reddys Laboratories": "Dr. Reddy's Laboratories",
        "Bayer HealthCare": "Bayer HealthCare",
        "Glaxosmithkline": "GlaxoSmithKline",
        "Novartis Consumer Health": "Novartis Consumer Health",
        "Johnson & Johnson Consumer": "Johnson & Johnson",
        "Pfizer Consumer Healthcare": "Pfizer",
        "Sanofi Aventis": "Sanofi",
        "Bayer Healthcare": "Bayer",
    }
    for orig, repl in name_map.items():
        if name.lower() == orig.lower():
            return repl
    return name


def main():
    filepath = "mock_data/drugs.json"
    with open(filepath, "r", encoding="utf-8") as f:
        drugs = json.load(f)

    logger.info(f"Translating {len(drugs)} drugs to Vietnamese...")
    for i, drug in enumerate(drugs):
        drug["name"] = translate_drug_name(drug["name"])[:200]
        drug["manufacturer"] = translate_manufacturer(drug.get("manufacturer", ""))[:200]
        drug["component"] = translate_text(drug.get("component", ""))[:500]
        drug["usage_info"] = translate_text(drug.get("usage_info", ""))[:1000]
        drug["dosage"] = translate_text(drug.get("dosage", ""))[:500]
        drug["side_effects"] = translate_text(drug.get("side_effects", ""))[:1000]
        drug["contraindications"] = translate_text(drug.get("contraindications", ""))[:1000]
        if (i + 1) % 50 == 0:
            logger.info(f"  Translated {i + 1}/{len(drugs)} drugs")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(drugs, f, ensure_ascii=False, indent=2)

    logger.info(f"Done! Translated {len(drugs)} drugs to Vietnamese.")


if __name__ == "__main__":
    main()
